## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [16]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [32]:
import numpy as np
import pandas as pd
# Type your solution here
#question 1-1
df= pd.DataFrame(data = data)
df

name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

In [31]:
#question1-2
df = df[(df['job'] == 'teacher') | (df['job'] == 'psychologist')]
df[df['num_cars'] > df['family_size']]

name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [34]:
#question 1-3
df[(df['num_cars']>=1) & (df['num_cars']<=2)]

name                 job  family_size  num_cars
1  Jacob        psychologist            2         1
2    Sam      data scientist            1         1
3  Jesee  software developer            4         2
4   Ryan        psychologist            2         2
6    Lee             teacher            2         1

In [38]:
#Question 1-4
df.job.unique()

array(['teacher', 'psychologist', 'data scientist', 'software developer'],
      dtype=object)

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [39]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [46]:
# Type your solution here
#Qustion 2 
dictionary = {'Fruit': fruit,'Weights':weights}
df = pd.DataFrame(dictionary)
np.mean(df['Weights'])


5.5

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [2]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [3]:
# Type your solution here
#Q3-1
sorted_index = np.sort(course_name)
for index,value in enumerate(sorted_index):
  print(value, ':', index)

JS : 0
PHP : 1
Python : 2
examples : 3
html : 4


In [35]:
list1 = []
for x in course_name:
  if 'P' in x:
    list1.append(x)
arr = np.array(list1)
pwords = np.char.startswith(arr, "P")
print(pwords)

[ True  True]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [58]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [61]:
# Type your solution here
#Q4-1
print(student_id[::-1])
print(student_id)

[4532 5241 1682 1671 6230 5202 1023]
[1023 5202 6230 1671 1682 5241 4532]


In [68]:
#question 4-2
sort_np = np.sort(student_id)
sort_np[-3:]

array([5202, 5241, 6230])

# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [86]:
# Type your solution here

# Hint: you can use arange to start off
#question 5 
onehundred = np.arange(100)
multiples = np.where((onehundred % 3 == 0) | (onehundred % 5 == 0))
print(np.sum(multiples))

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [49]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
# Type your solution here
#question 6-1
arr[:,[1,2]] = arr[:,[2,1]]
arr

array([[ 0,  2,  1,  3],
       [ 4,  6,  5,  7],
       [ 8, 10,  9, 11]])

In [57]:
#question 6-2
arr[[0,1],:] = arr[[1,0],:]
arr

array([[ 4,  6,  5,  7],
       [ 0,  2,  1,  3],
       [ 8, 10,  9, 11]])